# Generated by Django 4.0.1 on 2022-05-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211213_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_image', models.FileField(upload_to='processImages')),
            ],
        ),
        migrations.AlterField(
            model_name='rp',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
