import React from "react";
import { Button} from "react-bootstrap";
import CardLeft from "../HelperComponents/CardLeft";
import CardRight from "../HelperComponents/CardRight";
import "../components/maincomponents.scss";
import { Link } from "react-router-dom";


const HomePage = ()=>{

    // const HomeImageStyle={
    //     height: "300px",
    //     backgroundColor: "#848BB3",
    //     position:"relative",
    //     textAlign:"center",
    //     background-color: #36096d,
    //     background-image: linear-gradient(315deg, #36096d 0%, #37d5d6 74%);
    // }

    const HomePageButton={
        paddingLeft: "20px",
        paddingRight: "20px",
        paddingTop:"10px",
        paddingBottom:"10px",
        borderRadius: "7px",
        position: "absolute",
        right: "150px",
        bottom: "70px",
        opacity:1.0,
    }
    
    const HomeImageText={
        position: "absolute",
        left: "50px",
        bottom: "70px",
        color:"white",
        opacity:1.0,
        textShadow:"3px 3px black",
    }


    return (
        <center>
        <div className ="homeImageStyle" >
            <h1 className="HomeImageText" style={HomeImageText}>Research Paper Summarizer </h1>

            <Link
                style={{textDecoration: "none"}}
                
                to={{
                    pathname: "/UploadDoc",
                }}
                > 
                <Button variant="success" className="HomePageButton" style={HomePageButton}>Get Started</Button>
            </Link>
        </div>
        <div className="col-sm-10">
        <CardLeft 
        title="Generate Sectionwise Summary"
        content="
        As research paper summarizer, RPS generate a summary table that contains section-wise summary of 
        reserach paper uploaded. This summary generally consist of important points and defination in that section.
        This tools generates summary for IEEE/Springer format. This section-wise summary is generated by in depth analysis 
        of each topic in the research paper uploaded.
        "
        ></CardLeft>
        <CardRight
        title="Compare Summary Of Various Research Paper"
        content="
        RPS helps to compare summaries of research papers on the basis of common sections in a tabular format. 
        You can get an idea how other papers differ from others which will helps in comparative study of multiple research papers. 

        "
        ></CardRight>
        <CardLeft 
        title="Reduce Time For Summarization"
        content=" 
        In order to study any particular topic or the related works, one has to go through hundreds of websites and 
        related scientific journals which consumes a significant amount of time and energy, which may even take months. 
        RPS helps by identifying key information of important sections of all the related papers such as theme, related 
        study, approach and observations, which helps researchers and students reduce their majority of time."
        ></CardLeft>
        </div>
        </center>
    );
}



export default HomePage;